package org.alter.plugins.content.npcs.dungeon

import org.alter.api.ElementalWeakness
import org.alter.api.Elements
import org.alter.game.model.combat.CombatStyle
import org.alter.plugins.content.npcs.WeightedDrop

/**
 * The residents of the Ogre Enclave, the Temple of Ikov, Taverley Dungeon and the Yanille
 * Agility Dungeon - the four dungeons where the area packages had already placed giant bats and
 * everything standing next to them was still running on
 * [org.alter.game.model.combat.NpcCombatDef]'s 10-hitpoint defaults.
 *
 * Every number here is the wiki's, read off each monster's `Infobox Monster` for the exact
 * combat level that dungeon lists, and every npc id was checked against this cache's own
 * `npc.rscm` before wiring. Where a page publishes several versions of one level - nine
 * hill giants, twenty ghosts, ten black demons - all of that level's ids are included,
 * since they are mechanically identical and differ only in appearance.
 *
 * **Respawns are the wiki's `respawn` field verbatim.** That field is in game ticks,
 * which are this engine's cycles one-for-one, so nothing is converted. The suit of
 * armour and the baby black dragon are the only two whose field is blank on the wiki;
 * both fall back to 30 ticks, the commonest value across the rest of this file.
 *
 * **This file is stats, not mechanics.** Seven monsters from these dungeons are deliberately
 * absent, because they need behaviour this server does not have and a stat block alone would
 * make them spawn half-working:
 *
 * - **Blue dragon** (111) and **black dragon** (227) - dragonfire. Without it they would be
 *   ordinary melee monsters carrying a boss's stats, and antifire gear would do nothing.
 * - **Cerberus** (318) - a full boss: summoned souls, lava pools, phase behaviour.
 * - **Ogre shaman** (113) and **Salarin the twisted** (70) - magic attackers. This codebase
 *   has no generic NPC magic path at all (see `content/npcs/darkwizard`), so each needs its
 *   own attack loop.
 * - **Fire Warrior of Lesarkus** (84) - damageable only with ice arrows, a per-monster
 *   damage gate that does not exist here.
 * - **Guardian of Armadyl** - a quest NPC with no standalone combat block.
 *
 * The **baby** dragons are here rather than in that list: baby blue and baby black dragons
 * have no dragonfire in OSRS, so they genuinely are melee stat blocks.
 *
 * **Two things the wiki publishes that this engine cannot express**, flagged rather than
 * faked:
 *
 * 1. **Poison.** The poison scorpion (`Yes (3)`) and poison spider (`Yes (6)`) both poison
 *    on hit. `NpcCombatDef.poisonChance` exists and the DSL sets it, but **nothing in the
 *    engine ever reads it** - the only mentions outside the def and the DSL are CowPlugin
 *    setting it to 0.0 - so filling it in would be theatre. Both are wired as ordinary melee
 *    monsters and will not poison.
 * 2. **The chaos druid's magic.** Its attack style is "Crush, Magic" and its observed
 *    animation set includes 710 (`Animation.DRUID_BIND`), but the wiki quotes only a melee
 *    max hit, so it is wired crush-only. That is unlike the monk of Zamorak, excluded above,
 *    where magic is the dominant attack at 13 against 5 melee; a melee-only chaos druid is
 *    close to the real thing, a melee-only monk would not be.
 *
 * **Drops are wired in full**, in [DungeonDrops]: every 100% row, every weighted main-table
 * row, and a roll on the shared [org.alter.plugins.content.npcs.GemDropTable] for the eleven
 * monsters that reach it, at each one's own published rate (1/128 to 5/128).
 *
 * **Drop tables are read per drop version, not per combat level**, because the wiki splits
 * them that way and the two do not line up. A level 22 skeleton has one `Unarmed` id with a
 * 23-row table and three `Plain` ids that drop bones and almost nothing else; the same is
 * true at 25 and 45. Wiring one table per level would have handed three quarters of the
 * skeletons in these dungeons a table they never roll. The demons are the mirror image:
 * their id lists span `Regular` and `Chasm of Fire`, and only the `Regular` table is used
 * here - the handful of Chasm ids among them will roll the wrong one until that area exists
 * and can claim its own ids.
 *
 * Animations come from this project's own observed sets per npc id, cross-checked against
 * [org.alter.api.cfg.Animation]'s named constants - the reliable method, since
 * `MonsterAnimationResolver`'s duration heuristic mislabels attack against block for
 * humanoids. Every triple matched a named constant group (`SKELETON_*`, `DEMON_*`,
 * `GIANT_*`, `DWARF_*`, `OGRE_*`, `SCORPION_*`, `MAGIC_AXE_*`, `BABYDRAGON_*`,
 * `HUMAN_SLASH_SWORD_*`, `GHOST` in `named-combat-media.json`) except the hellhound, whose
 * block animation is the remaining member of its observed set once `FOX_ATTACK` and
 * `WOLF_DEATH` are accounted for.
 *
 * The suit of armour is `aggressive = Yes to whoever causes them to animate` - conditional
 * on an animate mechanic that does not exist here - so it is wired passive rather than
 * aggressive to everyone, which is what a plain reading of "Yes" would have produced.
 */
internal data class DungeonMonster(
    val name: String,
    val combatLevel: Int,
    val npcKeys: List<String>,
    val hitpoints: Int,
    val attack: Int,
    val strength: Int,
    val defence: Int,
    val attackSpeed: Int,
    val combatStyle: CombatStyle,
    val attackBonus: Int,
    val strengthBonus: Int,
    val defenceStab: Int,
    val defenceSlash: Int,
    val defenceCrush: Int,
    val defenceMagic: Int,
    val defenceRanged: Int,
    val slayerXp: Double,
    val respawnCycles: Int,
    val attackAnimation: Int,
    val blockAnimation: Int,
    val deathAnimation: Int,
    /** Aggro radius in tiles, or 0 where the wiki says the monster is not aggressive. */
    val aggroRadius: Int = 0,
    val elementalWeakness: ElementalWeakness? = null,
    /** rscm item keys dropped on every kill - the wiki's 100% section. */
    val guaranteedDrops: List<String> = emptyList(),
    /** One roll on this table per kill, if non-empty. */
    val table: List<WeightedDrop> = emptyList(),
    /** Chance of also rolling the shared gem drop table, or null if this monster never does. */
    val gemTableChance: Double? = null,
)

internal object DungeonMonsters {
    /** Wiki mage = 1 and range = 1 on every monster in this file. */
    const val MAGIC_LEVEL = 1
    const val RANGED_LEVEL = 1

    val ALL: List<DungeonMonster> =
        listOf(
        DungeonMonster(
            name = "Skeleton (level 22, unarmed)",
            combatLevel = 22,
            npcKeys = listOf("npc.skeleton"),
            hitpoints = 29,
            attack = 15,
            strength = 18,
            defence = 17,
            attackSpeed = 4,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 5,
            defenceSlash = 5,
            defenceCrush = -5,
            defenceMagic = 0,
            defenceRanged = 5,
            slayerXp = 29.0,
            respawnCycles = 70,
            attackAnimation = 5485,
            blockAnimation = 5489,
            deathAnimation = 5491,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.EARTH, 35),
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.SKELETON_LEVEL_22_UNARMED,
            gemTableChance = 1.0 / 128.0,
        ),
        DungeonMonster(
            name = "Skeleton (level 22)",
            combatLevel = 22,
            npcKeys = listOf("npc.skeleton_71", "npc.skeleton_72", "npc.skeleton_73"),
            hitpoints = 29,
            attack = 15,
            strength = 18,
            defence = 17,
            attackSpeed = 4,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 5,
            defenceSlash = 5,
            defenceCrush = -5,
            defenceMagic = 0,
            defenceRanged = 5,
            slayerXp = 29.0,
            respawnCycles = 70,
            attackAnimation = 5485,
            blockAnimation = 5489,
            deathAnimation = 5491,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.EARTH, 35),
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.SKELETON_LEVEL_22,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Skeleton (level 25, armed)",
            combatLevel = 25,
            npcKeys = listOf("npc.skeleton_77"),
            hitpoints = 17,
            attack = 24,
            strength = 24,
            defence = 24,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 15,
            strengthBonus = 14,
            defenceStab = 9,
            defenceSlash = 11,
            defenceCrush = -2,
            defenceMagic = 1,
            defenceRanged = 4,
            slayerXp = 17.0,
            respawnCycles = 60,
            attackAnimation = 5485,
            blockAnimation = 5489,
            deathAnimation = 5491,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.EARTH, 35),
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.SKELETON_LEVEL_25_ARMED,
            gemTableChance = 2.0 / 128.0,
        ),
        DungeonMonster(
            name = "Skeleton (level 25)",
            combatLevel = 25,
            npcKeys = listOf("npc.skeleton_78", "npc.skeleton_79", "npc.skeleton_80", "npc.skeleton_81"),
            hitpoints = 17,
            attack = 24,
            strength = 24,
            defence = 24,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 15,
            strengthBonus = 14,
            defenceStab = 9,
            defenceSlash = 11,
            defenceCrush = -2,
            defenceMagic = 1,
            defenceRanged = 4,
            slayerXp = 17.0,
            respawnCycles = 60,
            attackAnimation = 5485,
            blockAnimation = 5489,
            deathAnimation = 5491,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.EARTH, 35),
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.SKELETON_LEVEL_25,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Skeleton (level 45, armed)",
            combatLevel = 45,
            npcKeys = listOf("npc.skeleton_82"),
            hitpoints = 59,
            attack = 32,
            strength = 35,
            defence = 36,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 15,
            strengthBonus = 14,
            defenceStab = 9,
            defenceSlash = 11,
            defenceCrush = -2,
            defenceMagic = 1,
            defenceRanged = 4,
            slayerXp = 59.0,
            respawnCycles = 60,
            attackAnimation = 5499,
            blockAnimation = 5501,
            deathAnimation = 5503,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.EARTH, 35),
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.SKELETON_LEVEL_45_ARMED,
            gemTableChance = 2.0 / 128.0,
        ),
        DungeonMonster(
            name = "Skeleton (level 45)",
            combatLevel = 45,
            npcKeys = listOf("npc.skeleton_83"),
            hitpoints = 59,
            attack = 32,
            strength = 35,
            defence = 36,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 15,
            strengthBonus = 14,
            defenceStab = 9,
            defenceSlash = 11,
            defenceCrush = -2,
            defenceMagic = 1,
            defenceRanged = 4,
            slayerXp = 59.0,
            respawnCycles = 60,
            attackAnimation = 5499,
            blockAnimation = 5501,
            deathAnimation = 5503,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.EARTH, 35),
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.SKELETON_LEVEL_45,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Ghost",
            combatLevel = 19,
            npcKeys = listOf("npc.ghost", "npc.ghost_86", "npc.ghost_87", "npc.ghost_88", "npc.ghost_89", "npc.ghost_90", "npc.ghost_91", "npc.ghost_92", "npc.ghost_93", "npc.ghost_95", "npc.ghost_97", "npc.ghost_99", "npc.ghost_472", "npc.ghost_473", "npc.ghost_474", "npc.ghost_505", "npc.ghost_506", "npc.ghost_507", "npc.ghost_7263", "npc.ghost_7264"),
            hitpoints = 25,
            attack = 13,
            strength = 13,
            defence = 18,
            attackSpeed = 4,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 5,
            defenceSlash = 5,
            defenceCrush = 5,
            defenceMagic = -5,
            defenceRanged = 5,
            slayerXp = 25.0,
            respawnCycles = 40,
            attackAnimation = 5532,
            blockAnimation = 5533,
            deathAnimation = 5534,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.AIR, 50),
            guaranteedDrops = emptyList(),
            table = DungeonDrops.GHOST,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Suit of armour",
            combatLevel = 19,
            npcKeys = listOf("npc.suit_of_armour_5043"),
            hitpoints = 29,
            attack = 16,
            strength = 14,
            defence = 9,
            attackSpeed = 5,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 8,
            strengthBonus = 10,
            defenceStab = 46,
            defenceSlash = 50,
            defenceCrush = 45,
            defenceMagic = -12,
            defenceRanged = 45,
            slayerXp = 0.0,
            respawnCycles = 30,
            attackAnimation = 390,
            blockAnimation = 388,
            deathAnimation = 836,
            aggroRadius = 0,
            guaranteedDrops = emptyList(),
            table = DungeonDrops.SUIT_OF_ARMOUR,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Dwarf",
            combatLevel = 10,
            npcKeys = listOf("npc.dwarf_290", "npc.dwarf_296", "npc.dwarf_1405"),
            hitpoints = 16,
            attack = 8,
            strength = 8,
            defence = 6,
            attackSpeed = 5,
            combatStyle = CombatStyle.STAB,
            attackBonus = 5,
            strengthBonus = 7,
            defenceStab = 0,
            defenceSlash = 0,
            defenceCrush = 0,
            defenceMagic = 5,
            defenceRanged = 0,
            slayerXp = 16.0,
            respawnCycles = 25,
            attackAnimation = 99,
            blockAnimation = 100,
            deathAnimation = 102,
            aggroRadius = 0,
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.DWARF,
            gemTableChance = 1.0 / 128.0,
        ),
        DungeonMonster(
            name = "Chaos dwarf",
            combatLevel = 48,
            npcKeys = listOf("npc.chaos_dwarf"),
            hitpoints = 61,
            attack = 38,
            strength = 42,
            defence = 28,
            attackSpeed = 4,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 13,
            strengthBonus = 9,
            defenceStab = 40,
            defenceSlash = 34,
            defenceCrush = 25,
            defenceMagic = 10,
            defenceRanged = 35,
            slayerXp = 61.0,
            respawnCycles = 14,
            attackAnimation = 99,
            blockAnimation = 100,
            deathAnimation = 102,
            aggroRadius = 4,
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.CHAOS_DWARF,
            gemTableChance = 5.0 / 128.0,
        ),
        DungeonMonster(
            name = "Chaos druid",
            combatLevel = 13,
            npcKeys = listOf("npc.chaos_druid"),
            hitpoints = 20,
            attack = 8,
            strength = 8,
            defence = 12,
            attackSpeed = 4,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 0,
            defenceSlash = 0,
            defenceCrush = 0,
            defenceMagic = 0,
            defenceRanged = 0,
            slayerXp = 20.0,
            respawnCycles = 25,
            attackAnimation = 422,
            blockAnimation = 425,
            deathAnimation = 836,
            aggroRadius = 4,
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.CHAOS_DRUID,
            gemTableChance = 1.0 / 128.0,
        ),
        DungeonMonster(
            name = "Chaos druid warrior",
            combatLevel = 37,
            npcKeys = listOf("npc.chaos_druid_warrior"),
            hitpoints = 40,
            attack = 32,
            strength = 34,
            defence = 25,
            attackSpeed = 5,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 9,
            strengthBonus = 5,
            defenceStab = 13,
            defenceSlash = 17,
            defenceCrush = 14,
            defenceMagic = -4,
            defenceRanged = 14,
            slayerXp = 40.0,
            respawnCycles = 50,
            attackAnimation = 401,
            blockAnimation = 403,
            deathAnimation = 836,
            aggroRadius = 4,
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.CHAOS_DRUID_WARRIOR,
            gemTableChance = 1.0 / 128.0,
        ),
        DungeonMonster(
            name = "Poison scorpion",
            combatLevel = 20,
            npcKeys = listOf("npc.poison_scorpion"),
            hitpoints = 23,
            attack = 16,
            strength = 17,
            defence = 15,
            attackSpeed = 4,
            combatStyle = CombatStyle.STAB,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 5,
            defenceSlash = 15,
            defenceCrush = 15,
            defenceMagic = 0,
            defenceRanged = 5,
            slayerXp = 23.0,
            respawnCycles = 25,
            attackAnimation = 6254,
            blockAnimation = 6255,
            deathAnimation = 6256,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.FIRE, 25),
            guaranteedDrops = emptyList(),
            table = DungeonDrops.POISON_SCORPION,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Hill giant",
            combatLevel = 28,
            npcKeys = listOf("npc.hill_giant", "npc.hill_giant_13502", "npc.hill_giant_2099", "npc.hill_giant_13503", "npc.hill_giant_2100", "npc.hill_giant_13504", "npc.hill_giant_2101", "npc.hill_giant_2102", "npc.hill_giant_2103", "npc.hill_giant_12848", "npc.hill_giant_12849", "npc.hill_giant_12850"),
            hitpoints = 35,
            attack = 18,
            strength = 22,
            defence = 26,
            attackSpeed = 6,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 18,
            strengthBonus = 16,
            defenceStab = 0,
            defenceSlash = 0,
            defenceCrush = 0,
            defenceMagic = 0,
            defenceRanged = 0,
            slayerXp = 35.0,
            respawnCycles = 30,
            attackAnimation = 4652,
            blockAnimation = 4651,
            deathAnimation = 4653,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.EARTH, 25),
            guaranteedDrops = listOf("item.big_bones"),
            table = DungeonDrops.HILL_GIANT,
            gemTableChance = 3.0 / 128.0,
        ),
        DungeonMonster(
            name = "Magic axe",
            combatLevel = 42,
            npcKeys = listOf("npc.magic_axe", "npc.magic_axe_7269"),
            hitpoints = 44,
            attack = 38,
            strength = 38,
            defence = 29,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 10,
            defenceSlash = 5,
            defenceCrush = 15,
            defenceMagic = 5,
            defenceRanged = 10,
            slayerXp = 44.0,
            respawnCycles = 30,
            attackAnimation = 185,
            blockAnimation = 186,
            deathAnimation = 188,
            aggroRadius = 4,
            guaranteedDrops = listOf("item.iron_battleaxe"),
            table = DungeonDrops.MAGIC_AXE,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Jailer",
            combatLevel = 47,
            npcKeys = listOf("npc.jailer"),
            hitpoints = 47,
            attack = 40,
            strength = 40,
            defence = 40,
            attackSpeed = 4,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 79,
            defenceSlash = 63,
            defenceCrush = 47,
            defenceMagic = 0,
            defenceRanged = 0,
            slayerXp = 0.0,
            respawnCycles = 50,
            attackAnimation = 422,
            blockAnimation = 425,
            deathAnimation = 836,
            aggroRadius = 0,
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.JAILER,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Black Knight",
            combatLevel = 33,
            npcKeys = listOf("npc.black_knight_517", "npc.black_knight_4331", "npc.black_knight_11953", "npc.black_knight", "npc.black_knight_11952"),
            hitpoints = 42,
            attack = 25,
            strength = 25,
            defence = 25,
            attackSpeed = 5,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 18,
            strengthBonus = 16,
            defenceStab = 73,
            defenceSlash = 76,
            defenceCrush = 70,
            defenceMagic = -11,
            defenceRanged = 72,
            slayerXp = 42.0,
            respawnCycles = 25,
            attackAnimation = 390,
            blockAnimation = 388,
            deathAnimation = 836,
            aggroRadius = 4,
            guaranteedDrops = listOf("item.bones"),
            table = DungeonDrops.BLACK_KNIGHT,
            gemTableChance = 3.0 / 128.0,
        ),
        DungeonMonster(
            name = "Baby blue dragon",
            combatLevel = 48,
            npcKeys = listOf("npc.baby_blue_dragon", "npc.baby_blue_dragon_242", "npc.baby_blue_dragon_243", "npc.baby_blue_dragon_14105", "npc.baby_blue_dragon_14106"),
            hitpoints = 50,
            attack = 40,
            strength = 40,
            defence = 40,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 0,
            defenceSlash = 50,
            defenceCrush = 50,
            defenceMagic = 40,
            defenceRanged = 30,
            slayerXp = 50.0,
            respawnCycles = 30,
            attackAnimation = 25,
            blockAnimation = 26,
            deathAnimation = 28,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.WATER, 50),
            guaranteedDrops = listOf("item.babydragon_bones"),
            table = DungeonDrops.BABY_BLUE_DRAGON,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Baby black dragon",
            combatLevel = 83,
            npcKeys = listOf("npc.baby_black_dragon", "npc.baby_black_dragon_1872", "npc.baby_black_dragon_7955"),
            hitpoints = 80,
            attack = 70,
            strength = 70,
            defence = 70,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 0,
            defenceSlash = 50,
            defenceCrush = 50,
            defenceMagic = 40,
            defenceRanged = 30,
            slayerXp = 80.0,
            respawnCycles = 30,
            attackAnimation = 25,
            blockAnimation = 26,
            deathAnimation = 28,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.WATER, 50),
            guaranteedDrops = listOf("item.babydragon_bones"),
            table = DungeonDrops.BABY_BLACK_DRAGON,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Poison spider",
            combatLevel = 64,
            npcKeys = listOf("npc.poison_spider", "npc.poison_spider_11999"),
            hitpoints = 64,
            attack = 50,
            strength = 58,
            defence = 52,
            attackSpeed = 4,
            combatStyle = CombatStyle.STAB,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 20,
            defenceSlash = 17,
            defenceCrush = 10,
            defenceMagic = 14,
            defenceRanged = 14,
            slayerXp = 64.0,
            respawnCycles = 30,
            attackAnimation = 5327,
            blockAnimation = 5328,
            deathAnimation = 5329,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.FIRE, 40),
            guaranteedDrops = emptyList(),
            table = DungeonDrops.POISON_SPIDER,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Ice spider",
            combatLevel = 61,
            npcKeys = listOf("npc.ice_spider", "npc.ice_spider_10722", "npc.ice_spider_13798"),
            hitpoints = 65,
            attack = 50,
            strength = 55,
            defence = 43,
            attackSpeed = 4,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 20,
            defenceSlash = 17,
            defenceCrush = 12,
            defenceMagic = 13,
            defenceRanged = 13,
            slayerXp = 65.0,
            respawnCycles = 30,
            attackAnimation = 5327,
            blockAnimation = 5328,
            deathAnimation = 5329,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.FIRE, 100),
            guaranteedDrops = emptyList(),
            table = DungeonDrops.ICE_SPIDER,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Lesser demon",
            combatLevel = 82,
            npcKeys = listOf("npc.lesser_demon", "npc.lesser_demon_2006", "npc.lesser_demon_2007", "npc.lesser_demon_2008", "npc.lesser_demon_2018", "npc.lesser_demon_7656", "npc.lesser_demon_7657", "npc.lesser_demon_7664"),
            hitpoints = 79,
            attack = 68,
            strength = 70,
            defence = 71,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 0,
            defenceSlash = 0,
            defenceCrush = 0,
            defenceMagic = -10,
            defenceRanged = 0,
            slayerXp = 79.0,
            respawnCycles = 30,
            attackAnimation = 64,
            blockAnimation = 65,
            deathAnimation = 67,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.WATER, 40),
            guaranteedDrops = listOf("item.vile_ashes"),
            table = DungeonDrops.LESSER_DEMON,
            gemTableChance = 4.0 / 128.0,
        ),
        DungeonMonster(
            name = "Greater demon",
            combatLevel = 92,
            npcKeys = listOf("npc.greater_demon", "npc.greater_demon_2026", "npc.greater_demon_2027", "npc.greater_demon_2028", "npc.greater_demon_2029", "npc.greater_demon_2030", "npc.greater_demon_2031", "npc.greater_demon_2032"),
            hitpoints = 87,
            attack = 76,
            strength = 78,
            defence = 81,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 0,
            defenceSlash = 0,
            defenceCrush = 0,
            defenceMagic = -10,
            defenceRanged = 0,
            slayerXp = 87.0,
            respawnCycles = 15,
            attackAnimation = 64,
            blockAnimation = 65,
            deathAnimation = 67,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.WATER, 40),
            guaranteedDrops = listOf("item.vile_ashes"),
            table = DungeonDrops.GREATER_DEMON,
            gemTableChance = 5.0 / 128.0,
        ),
        DungeonMonster(
            name = "Black demon",
            combatLevel = 172,
            npcKeys = listOf("npc.black_demon", "npc.black_demon_2048", "npc.black_demon_2049", "npc.black_demon_2050", "npc.black_demon_2051", "npc.black_demon_2052", "npc.black_demon_5874", "npc.black_demon_5875", "npc.black_demon_5876", "npc.black_demon_5877"),
            hitpoints = 157,
            attack = 145,
            strength = 148,
            defence = 152,
            attackSpeed = 4,
            combatStyle = CombatStyle.SLASH,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 0,
            defenceSlash = 0,
            defenceCrush = 0,
            defenceMagic = -10,
            defenceRanged = 0,
            slayerXp = 157.0,
            respawnCycles = 30,
            attackAnimation = 64,
            blockAnimation = 65,
            deathAnimation = 67,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.WATER, 40),
            guaranteedDrops = listOf("item.malicious_ashes"),
            table = DungeonDrops.BLACK_DEMON,
            gemTableChance = 5.0 / 128.0,
        ),
        DungeonMonster(
            name = "Hellhound",
            combatLevel = 122,
            npcKeys = listOf("npc.hellhound_104", "npc.hellhound_105", "npc.hellhound_7256"),
            hitpoints = 116,
            attack = 105,
            strength = 104,
            defence = 102,
            attackSpeed = 4,
            combatStyle = CombatStyle.STAB,
            attackBonus = 0,
            strengthBonus = 0,
            defenceStab = 0,
            defenceSlash = 0,
            defenceCrush = 0,
            defenceMagic = 0,
            defenceRanged = 0,
            slayerXp = 116.0,
            respawnCycles = 89,
            attackAnimation = 6562,
            blockAnimation = 6566,
            deathAnimation = 6576,
            aggroRadius = 4,
            elementalWeakness = ElementalWeakness(Elements.WATER, 50),
            guaranteedDrops = listOf("item.vile_ashes"),
            table = DungeonDrops.HELLHOUND,
            gemTableChance = null,
        ),
        DungeonMonster(
            name = "Ogre chieftain",
            combatLevel = 81,
            npcKeys = listOf("npc.ogre_chieftain"),
            hitpoints = 60,
            attack = 75,
            strength = 71,
            defence = 75,
            attackSpeed = 4,
            combatStyle = CombatStyle.CRUSH,
            attackBonus = 5,
            strengthBonus = 7,
            defenceStab = 10,
            defenceSlash = 21,
            defenceCrush = 16,
            defenceMagic = 0,
            defenceRanged = 0,
            slayerXp = 60.0,
            respawnCycles = 300,
            attackAnimation = 359,
            blockAnimation = 360,
            deathAnimation = 361,
            aggroRadius = 0,
            elementalWeakness = ElementalWeakness(Elements.EARTH, 20),
            guaranteedDrops = listOf("item.big_bones"),
            table = DungeonDrops.OGRE_CHIEFTAIN,
            gemTableChance = null,
        ),
        )
}
